pipeline:
  branches:
    - name: main
      elements:
        - name: videotestsrc
        - name: nvvidconv
        - name: tee
          type: meta_tee
        - name: queue
        - name: analyticsaggregator
          type: mux
          sinkpad: video_sink
          properties:
            name: agg
            silent: true
        - name: nv3dsink

    - name: meta_tee
      optional: false
      elements:
        - name: queue
        - name: analyticsaggregator
          type: mux
          sinkpad: sink_0
          properties:
            name: agg
