pipeline:
  branches:
    - name: main
      elements:
        - name: videotestsrc
        - name: nvvidconv
        - name: capsfilter
          properties:
            caps: video/x-raw(memory:NVMM),format=I420,width=320,height=240,framerate=30/1
        - name: tee
          type: meta_tee
        - name: queue
        - name: nvstreammux
          type: mux
          sinkpad: sink_0
          properties:
            name: nvmux
            batch-size: 1
            width: 1920
            height: 1080
            batched-push-timeout: 40000
        - name: fakesink

    - name: meta_tee
      optional: true
      elements:
        - name: queue
        - name: nvstreammux
          type: mux
          sinkpad: sink_1
          properties:
            name: nvmux
