pipeline:
  elements:
############# Template Element #############
#    - name: videotestsrc
#      optional: true
#      properties:
#        pattern: smpte
#        num-buffers: 50
############################################
    - name: videotestsrc
      type: source
      properties:
        pattern: smpte
    - name: capsfilter
      properties:
        caps: video/x-raw,width=640,height=480,framerate=30/1
    - name: timeoverlay
      optional: true
    - name: tee
      type: tee
    - name: metadatainjector
      optional: true
    - name: metadataextractor
      optional: true
    - name: autovideosink
      type: sink
