pipeline:
  branches:
    - name: main
      elements:
        - name: videotestsrc
          properties:
            pattern: smpte
        - name: capsfilter
          properties:
            caps: video/x-raw,width=640,height=480,framerate=30/1
        - name: timeoverlay
          optional: true
        - name: tee
          type: atr_tee
        - name: autovideosink

    - name: atr_tee
      elements:
        - name: metadatainjector
          optional: true
        - name: tee
          type: vmd_tee
        - name: metadataextractor
          optional: true
        - name: autovideosink
#
#    - name: vmd_tee
#      elements:
#        - name: timeoverlay
#        - name: autovideosink
