pipeline:
  branches:
    - name: main
      elements:
        - name: videotestsrc
          properties:
            pattern: ball
        - name: capsfilter
          properties:
            caps: video/x-raw,format=UYVY,width=1920,height=1080,framerate=30/1
        - name: preprocessing
          optional: true
        - name: tee
          type: atr_tee
        - name: postprocessing
          optional: true
        - name: textoverlay
          properties:
            text: CAM1
            valignment: top
            halignment: left
        - name: timeoverlay
          properties:
            valignment: top
            halignment: right
        - name: nvvidconv
        - name: nvv4l2h264enc
        - name: h264parse
        - name: rtspclientsink
          properties:
            location: rtsp://localhost:8554/stream1

    - name: atr_tee
      optional: true
      elements:
        - name: queue
        - name: nvvidconv
        - name: nvstreammux
          properties:
            batch-size: 1
            width: 1920
            height: 1080
            batched-push-timeout: 40000
        - name: nvinfer
          properties:
            config-file-path: /home/fronti/Downloads/Primary_Detector/config.yml
        - name: fakesink
