pipeline:
  branches:
    - name: main
      elements:
        - name: videotestsrc
          properties:
            pattern: smpte
            num-buffers: 50
        - name: capsfilter
          properties:
            caps: video/x-raw,width=640,height=480,framerate=30/1
        - name: timeoverlay
        - name: autovideosink
