pipeline:
  branches:
    - name: main
      elements:
        - name: videotestsrc
          properties:
            pattern: smpte
        - name: capsfilter
          properties:
            caps: video/x-raw,width=640,height=480,framerate=30/1
        - name: tee
          type: atr_tee
        - name: timeoverlay
        - name: autovideosink

    - name: atr_tee
      elements:
        - name: autovideosink
