################################################################################
# SPDX-FileCopyrightText: Copyright (c) 2022 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.
################################################################################

# The following data schema will be added to the objects detected by nvinfer for data output purposes
# The parser suitable to this schema should be implemented and injected to nvmsgconv element by msg2p-lib property
# Parser lib example implementation: /opt/nvidia/deepstream/deepstream-7.0/sources/libs/nvmsgconv
#
# The parser is looking for sensor, place and analytics fields in the config file. 
# Each field in the config file is followed by a sensor ID.
# The sensor ID is determined by the tee src pad's ID (src_%u).

sensor1:
  enable: 1
  type: Camera
  id: Sony
  location: 45.293701447;-75.8303914499;48.1557479338
  description: "Frontier"
  coordinate: 5.2;10.1;11.2

place1:
  enable: 1
  id: 1
  type: place_field
  name: XYZ
  location: 30.32;-40.55;100.0
  coordinate: 1.0;2.0;3.0
  place-sub-field1: israel #id
  place-sub-field2: sderot #name
  place-sub-field3: elsec #level

analytics1:
  enable: 1
  id: XYZ
  description: "Frontier Analytics"
  source: OpenALR
  version: 1.0