pipeline:
  branches:
    - name: main
      elements:
        - name: v4l2src
          properties:
            device: /dev/video0
        - name: capsfilter
          properties:
            caps: video/x-raw,format=UYVY,width=1920,height=1080,framerate=30/1
        - name: preprocessing
          optional: true
        - name: postprocessing
          optional: true
        - name: textoverlay
          properties:
            text: CAM1
            valignment: top
            halignment: left
        - name: timeoverlay
          properties:
            valignment: top
            halignment: right
        - name: nvvideoconvert
        - name: nvv4l2h264enc
        - name: h264parse
        - name: rtspclientsink
          properties:
            location: rtsp://localhost:8554/stream1