name: Build and Run

on:
  push:
  pull_request:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Get repo name
      id: repo-name
      run: echo "name=$(echo "${{github.repository}}" | awk -F '/' '{print $2}')" >> $GITHUB_OUTPUT

    - name: Install dependencies
      run: sudo apt-get -y update && sudo apt-get install -y make libunwind-dev &&
        sudo apt-get -y install pkg-config libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
        libgstreamer-plugins-bad1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good
        gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly

    - name: Configure
      run: cmake -B build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build build --config ${{env.BUILD_TYPE}}

    - name: Run
      run: cd ./build && ./${{steps.repo-name.outputs.name}} -i ../resources/pipeline_test.yml -v
